version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=${mongodb+srv://user:Samsung01@dsai.hnzpx.mongodb.net/}
      - JWT_SECRET_KEY: 'my_jwt_super_mega_secret_key'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
